[project]
name = "quart-sqlalchemy"
version = "3.0.5"
description = "SQLAlchemy for humans, with framework adapter for Quart."
authors = [
    {name = "Joe Black", email = "me@joeblack.nyc"},
]
maintainers = [
    {name = "Joe Black", email = "me@joeblack.nyc"},
]
requires-python = ">=3.12,<3.14"
readme = "README.md"
license = {text = "MIT"}
classifiers = [
    "Development Status :: 3 - Alpha",
    "License :: OSI Approved :: MIT License",
    "Natural Language :: English",
    "Operating System :: OS Independent",
    "Programming Language :: Python",
    "Programming Language :: Python :: 3",
    "Programming Language :: Python :: 3.12",
    "Programming Language :: Python :: 3.13",
    "Topic :: Software Development",
    "Typing :: Typed",
    "Intended Audience :: Developers",
    "Topic :: Database",
    "Topic :: Database :: Database Engines/Servers",
]
keywords = ["sqlalchemy", "alembic", "fastapi", "flask", "quart"]
dependencies = [
    "blinker~=1.9.0",
    "sqlalchemy[asyncio]~=2.0.44",
    "sqlalchemy-utils",
    "aiosqlite>=0.20.0",
    "anyio~=4.11.0",
    "packaging~=25.0",
    "pydantic~=2.12.3",
    "tenacity~=9.1.2",
    "sqlapagination~=0.0.1",
    "uuid-utils~=0.11.1,; python_version < '3.14'",
]

[project.urls]
Homepage = "https://github.com/joeblackwaslike/quart-sqlalchemy"
Repository = "https://github.com/joeblackwaslike/quart-sqlalchemy"
Documentation = "https://joeblackwaslike.github.io/quart-sqlalchemy"
"Bug Tracker" = "https://github.com/joeblackwaslike/quart-sqlalchemy/issues"

[project.optional-dependencies]
test = [
    "asgi-lifespan~=2.1.0",
    "httpx~=0.28.1",
    "pytest~=8.4.2",
    "pytest-asyncio~=1.2.0",
    "pytest-mock~=3.15.1",
    "pytest-cov~=7.0.0",
    "coverage[toml]~=7.10.7",
    "tox~=4.31.0",
    "tox-uv~=1.29.0",
]

dev = [
    "ipython~=9.6.0",
    "pre-commit~=4.3.0",
    "mypy~=1.18.2",
    "ruff~=0.14.0",
]
quart = [
    "quart~=0.20.0",
    "werkzeug~=3.1.3",
]
fastapi = [
    "fastapi~=0.119.0",
    "starlette~=0.48.0",
    "typer~=0.11.1",
]
mysql = ["asyncmy>=0.2.9"]
postgres = ["psycopg[binary,pool]>=3.2.3"]


[build-system]
requires = ["setuptools >= 61.0"]
build-backend = "setuptools.build_meta"

[tool.setuptools]
py-modules = ["src"]

[tool.mypy]
# The mypy configurations: http://bit.ly/2zEl9WI
files = ["src"]
plugins = ["pydantic.mypy"]
strict = true
follow_imports = "silent"
warn_return_any = true
warn_redundant_casts = true
warn_unused_ignores = true
warn_unreachable = true
disallow_untyped_defs = true
disallow_any_unimported = true
no_implicit_optional = true
check_untyped_defs = true
show_error_codes = true

[tool.pydantic-mypy]
init_forbid_extra = true
init_typed = true
warn_required_dynamic_aliases = true

[[tool.mypy.overrides]]
module = [
    "cryptography.*",
    "sqlalchemy_utils.*",
]
ignore_missing_imports = true

[tool.ruff]
# Ruff config: https://docs.astral.sh/ruff/settings
target-version = "py312"
line-length = 100
fix = true
force-exclude = true
extend-exclude = [
    ".ruff_cache",
    ".claude",
    ".tox",
]

[tool.ruff.lint]
select = [
    "A",    # flake8-builtins
    "ASYNC210",
    "ASYNC212",
    "ASYNC220",
    "ASYNC221",
    "ASYNC222",
    "ASYNC230",
    "ASYNC250",
    "ASYNC251",
    "ARG",
    "B",    # flake8-bugbear
    "BLE",  # flake8-blind-except
    "C4",   # flake8-comprehensions
    "C90",  # maccabe
    "COM",  # flake8-commas
    "D",
    "DOC",    # pydocstyle
    "DTZ",  # flake8-datetimez
    "E",    # pycodestyle
    "ERA",  # flake8-eradicate
    "EXE",  # flake8-executable
    "F",    # pyflakes
    "FAST",
    "FBT",  # flake8-boolean-trap
    "FLY",  # pyflint
    "FURB", # refurb
    "G",    # flake8-logging-format
    "I",    # isort
    "ICN",  # flake8-import-conventions
    "ISC",  # flake8-implicit-str-concat
    "LOG",  # flake8-logging
    "N",
    "NPY",
    "PD",
    "PERF", # perflint
    "PIE",  # flake8-pie
    "PL",   # pylint
    "PT",   # flake8-pytest-style
    "PTH",  # flake8-use-pathlib
    "Q",    # flake8-quotes
    "RET",  # flake8-return
    "RSE",  # flake8-raise
    "RUF",  # ruff
    "S",    # flake8-bandit
    "SIM",  # flake8-simpify
    "SLF",  # flake8-self
    "SLOT", # flake8-slots
    "T100", # flake8-debugger
    "TC",
    "TD",
    "TRY",  # tryceratops
    "UP",   # pyupgrade
    "W",    # pycodestyle
    "YTT",  # flake8-2020
]
ignore = [
    "A002",
    "A003",
    "A005",
    "A006",   # allow to shadow stdlib and builtin module names
    "COM812", # trailing comma, conflicts with `ruff format`
    "C408",
    # Different doc rules that we don't really care about:
    # "D100",
    # "D104",
    "D106",
    # "D203",
    # "D212",
    # "D401",
    # "D404",
    # "D405",
    # "E501",    # line too long
    "E731",    # do not assign lambda
    "ISC001",  # implicit string concat conflicts with `ruff format`
    "ISC003",  # prefer explicit string concat over implicit concat
    "SIM117",
    "PLR09",   # we have our own complexity rules
    "PLR2004", # do not report magic numbers
    "PLR6301", # do not require classmethod / staticmethod when self not used
    "PTH123",
    "TRY003",  # long exception messages from `tryceratops`
]

[tool.ruff.lint.flake8-import-conventions]
banned-from = [ "ast" ]

[tool.ruff.lint.flake8-annotations]
allow-star-arg-any = true
ignore-fully-untyped = true
mypy-init-return = true

[tool.ruff.lint.flake8-boolean-trap]
extend-allowed-calls = ["pydantic.Field"]

[tool.ruff.lint.flake8-builtins]
builtins-ignorelist = ["id", "type",]

[tool.ruff.lint.flake8-comprehensions]
allow-dict-calls-with-keyword-arguments = true

[tool.ruff.lint.flake8-copyright]
author = "Joe Black"

[tool.ruff.lint.flake8-import-conventions.extend-aliases]
"typing" = "t"
"sqlalchemy" = "sa"

[tool.ruff.lint.isort]
known-first-party = ["quart_sqlalchemy", "tests"]

[tool.ruff.lint.mccabe]
max-complexity = 24

[tool.ruff.lint.pep8-naming]
classmethod-decorators = [
  "sqlalchemy.ext.declarative.declared_attr",
  "sqlalchemy.orm.declared_attr.directive",
  "sqlalchemy.orm.declared_attr",
  "pydantic.validator",
]

[tool.ruff.lint.pycodestyle]
ignore-overlong-task-comments = true

[tool.ruff.lint.pydocstyle]
convention = "google"


[tool.ruff.lint.per-file-ignores]
"__init__.py" = [
    "F401", # unused import
    "F403", # star imports
]
"tests/*.py" = [
  "S101", # asserts
  "S105", # hardcoded passwords
#   "S404", # subprocess calls are for tests
#   "S603", # do not require `shell=True`
#   "S607", # partial executable paths
  "D101",
#   "D102",
#   "D103",
  "N802",
  "N803", # docstrings on public functions
]

[tool.ruff.format]
preview = true
quote-style = "double"
indent-style = "space"
docstring-code-format = true

[tool.ty.src]
include = ["src", "tests"]

[tool.coverage.run]
branch = true
source = ["src", "tests"]

[tool.coverage.paths]
source = ["src"]

[tool.coverage.report]
skip_empty = true

[tool.pytest.ini_options]
# pytest config: http://doc.pytest.org/en/latest/customize.html
pythonpath = ["src"]
addopts = "-rsx --tb=short"
testpaths = ["tests"]
filterwarnings = ["error"]
asyncio_mode = "auto"
log_cli = true

[tool.codespell]
ignore-words-list = "selectin,fo,froms,notin"
skip = 'uv.lock'
